### ISSUE TITLE
OutofMemory when reading excel file with 100MB.

### ISSUE THREAD

**Issue by nguyen-thom** [jeevatkm/excelReader#4]
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191)
	at org.apache.poi.openxml4j.util.ZipInputStreamZipEntrySource$FakeZipEntry.<init>(ZipInputStreamZipEntrySource.java:136)
	at org.apache.poi.openxml4j.util.ZipInputStreamZipEntrySource.<init>(ZipInputStreamZipEntrySource.java:56)
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:100)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
	at jp.co.transcosmos.workload.engine.parse.LargeExcelWorkloadParser.getOPCPackage(LargeExcelWorkloadParser.java:163)
	at jp.co.transcosmos.workload.engine.parse.LargeExcelWorkloadParser.parseWorkload(LargeExcelWorkloadParser.java:72)
	at jp.co.transcosmos.workload.engine.parse.test.LargeExcelWorkloadParserTest.testParseSimple_101_001(LargeExcelWorkloadParserTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by nguyen-thom** [comment]
Please change code 
return OPCPackage.open(new FileInputStream(file));

To
 return OPCPackage.open(file, PackageAccess.READ);

**Comment by jeevatkm** [comment]
@thomnv Please feel free to send PR with your proposed changes, we can merge it in.

Later I will publish it maven central.

**Comment by jeevatkm** [comment]
@thomnv I have updated with your suggestion and released `v1.3` to maven central.
